# Generated by Django 4.2.1 on 2023-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f_reg',
            old_name='district',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='f_reg',
            old_name='experience',
            new_name='Experience',
        ),
        migrations.RenameField(
            model_name='f_reg',
            old_name='license_id',
            new_name='License_id',
        ),
        migrations.RenameField(
            model_name='f_reg',
            old_name='state',
            new_name='State',
        ),
        migrations.AddField(
            model_name='f_reg',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='f_reg',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
