# Generated by Django 4.2.1 on 2023-05-25 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_rename_district_f_reg_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=20)),
                ('p_type', models.CharField(max_length=20)),
                ('p_img', models.ImageField(upload_to='product')),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.f_reg')),
            ],
        ),
    ]
