# Generated by Django 4.2.1 on 2023-05-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_product_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tb',
            old_name='F_id',
            new_name='Fid',
        ),
    ]
