# Generated by Django 4.2.1 on 2023-06-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_rename_f_id_product_tb_fid'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookpond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('lessor', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
                ('breadth', models.IntegerField()),
                ('length', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('book', models.BooleanField(default=False)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.f_reg')),
            ],
        ),
    ]
