# Generated by Django 4.2.1 on 2023-06-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_bookpond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tb',
            old_name='quantity',
            new_name='avgwght',
        ),
        migrations.AddField(
            model_name='product_tb',
            name='Grade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
