# Generated by Django 4.2.1 on 2023-06-15 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_rename_quantity_product_tb_avgwght_product_tb_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedname', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('del_date', models.CharField(max_length=50)),
                ('del_time', models.CharField(max_length=50)),
                ('payment', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('book', models.BooleanField(default=False)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.f_reg')),
            ],
        ),
        migrations.DeleteModel(
            name='bookpond',
        ),
    ]
