# Generated by Django 4.2.1 on 2023-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_remove_book_feed_del_date_remove_book_feed_del_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f_reg',
            name='Experience',
            field=models.IntegerField(),
        ),
    ]
