# Generated by Django 4.2.1 on 2023-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_f_reg_whatsappno'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='upld_date',
            field=models.DateField(null=True, verbose_name='upld_date'),
        ),
        migrations.AddField(
            model_name='product_tb',
            name='upld_time',
            field=models.TimeField(null=True, verbose_name='upld_time'),
        ),
    ]
