# Generated by Django 4.2.1 on 2023-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_product_tb_upld_date_product_tb_upld_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_tb',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
