# Generated by Django 4.2.1 on 2023-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0002_pond_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pond_tb',
            old_name='L_id',
            new_name='Lid',
        ),
        migrations.AddField(
            model_name='pond_tb',
            name='pond_img',
            field=models.ImageField(default=1, upload_to='pond'),
            preserve_default=False,
        ),
    ]
