# Generated by Django 4.2.1 on 2023-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0003_rename_l_id_pond_tb_lid_pond_tb_pond_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond_tb',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
