# Generated by Django 4.2.1 on 2023-06-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0004_alter_pond_tb_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond_tb',
            name='Description',
            field=models.CharField(max_length=5000),
        ),
    ]
