# Generated by Django 4.2.1 on 2023-06-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0005_alter_pond_tb_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond_tb',
            name='breadth',
        ),
        migrations.RemoveField(
            model_name='pond_tb',
            name='facing',
        ),
        migrations.RemoveField(
            model_name='pond_tb',
            name='length',
        ),
        migrations.RemoveField(
            model_name='pond_tb',
            name='plot_area',
        ),
        migrations.AddField(
            model_name='pond_tb',
            name='cent',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pond_tb',
            name='district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pond_tb',
            name='phoneno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
