# Generated by Django 4.2.1 on 2023-06-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0006_remove_pond_tb_breadth_remove_pond_tb_facing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond_tb',
            name='cent',
            field=models.IntegerField(null=True),
        ),
    ]
