# Generated by Django 4.2.1 on 2023-06-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0007_alter_pond_tb_cent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond_tb',
            name='phoneno',
        ),
    ]
