# Generated by Django 4.2.1 on 2023-06-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessor', '0008_remove_pond_tb_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond_tb',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
