# Generated by Django 4.2.1 on 2023-05-31 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0003_ponds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ponds',
        ),
    ]
