# Generated by Django 4.2.1 on 2023-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0004_delete_ponds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishfeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedname', models.CharField(max_length=50)),
            ],
        ),
    ]
