# Generated by Django 4.2.1 on 2023-06-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0005_fishfeeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishfeeds',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fishfeeds',
            name='img',
            field=models.ImageField(null=True, upload_to='feed'),
        ),
        migrations.AddField(
            model_name='fishfeeds',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fishfeeds',
            name='feedname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
