# Generated by Django 4.2.1 on 2023-06-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0006_fishfeeds_description_fishfeeds_img_fishfeeds_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishfeeds',
            name='quantity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
