# Generated by Django 4.2.1 on 2023-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0007_fishfeeds_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishfeeds',
            name='img',
            field=models.ImageField(default=1, upload_to='feed'),
            preserve_default=False,
        ),
    ]
