# Generated by Django 4.2.1 on 2023-05-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='u_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_name', models.CharField(max_length=20)),
                ('House_name', models.CharField(max_length=50)),
                ('Street', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
                ('Phoneno', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
            ],
        ),
    ]
