# Generated by Django 4.2.1 on 2023-06-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_book_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_f',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book_f',
            name='book',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book_f',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book_f',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
