# Generated by Django 4.2.1 on 2023-06-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_book_f_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('breadth', models.IntegerField()),
                ('length', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('book', models.BooleanField(default=False)),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.u_reg')),
            ],
        ),
    ]
