# Generated by Django 4.2.1 on 2023-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_book_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_p',
            name='farmer',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
