# Generated by Django 4.2.1 on 2023-06-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_book_p_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_p',
            name='farmer',
        ),
        migrations.AddField(
            model_name='book_f',
            name='farmer',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
