# Generated by Django 4.2.1 on 2023-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_book_p_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_p',
            name='total',
        ),
        migrations.AddField(
            model_name='book_f',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
