# Generated by Django 4.2.1 on 2023-06-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_book_p_desc_book_p_lessor_book_p_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='h_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Street', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
                ('Phoneno', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Photo', models.ImageField(upload_to='hotel')),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
            ],
        ),
    ]
