# Generated by Django 4.2.1 on 2023-06-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_h_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_f',
            name='pac',
            field=models.IntegerField(null=True),
        ),
    ]
