# Generated by Django 4.2.1 on 2023-06-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_book_f_pac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_f',
            name='pac',
        ),
    ]
