# Generated by Django 4.2.1 on 2023-06-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_book_f_pac'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_f',
            name='avgwght',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
