# Generated by Django 4.2.1 on 2023-06-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_u_reg_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_p',
        ),
    ]
