# Generated by Django 4.2.1 on 2023-06-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_book_f_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='fishrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=20)),
                ('Uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.u_reg')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.book_f')),
            ],
        ),
    ]
