# Generated by Django 4.2.1 on 2023-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_fishrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_f',
            name='rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book_f',
            name='review',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='fishrate',
        ),
    ]
