# Generated by Django 4.1.5 on 2023-07-14 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0015_book_feed_billdate'),
        ('user', '0020_book_f_billdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='h_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total', models.IntegerField()),
                ('billdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('del_date', models.CharField(max_length=50)),
                ('payment', models.BooleanField(default=False)),
                ('accept', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('book', models.BooleanField(default=False)),
                ('hid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.h_reg')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.product_tb')),
            ],
        ),
    ]
